# Generated by Django 4.2.10 on 2024-02-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('is_site_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
