# Generated by Django 4.2.10 on 2024-03-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user_name',
        ),
        migrations.AddField(
            model_name='report',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
