# Generated by Django 4.2.11 on 2024-03-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='explain',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
