# Generated by Django 4.2.10 on 2024-03-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_report_date_report_explain_report_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
