# Generated by Django 4.2.10 on 2024-03-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_report_note_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Completed')], default=0),
        ),
    ]
