# Generated by Django 4.2.11 on 2024-03-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_report_note_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Resolved')], default=0),
        ),
    ]
