# Generated by Django 4.2.10 on 2024-04-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_report_file_reportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
